def generateID(self)
def soLuongSinhVien(self)
def nhapSinhVien(self)
def updateSinhVien(self, ID)
def sortByID(self)
def sortByName(self)
def sortByDiemTB(self)
def findByID(self, ID)
def findByName(self, keyword)
def deleteById(self, ID)
def tinhDTB(self, sv:SinhVien)
def showSinhVien(self, listSV)
def getListSinhVien(self)